
import json
import joblib
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
import os
import sys
path = os.path.join(os.path.dirname(__file__), "..")
if path not in sys.path:
    sys.path.append(path)
from src import config
from src.data_preprocessing import (
    get_clean_splits,)
from src.feature_engineering import (
    prepare_features,
    build_preprocessor,
)

from src.imbalance_cost import (
    get_scale_pos_weight,
    find_cost_optimal_threshold,
)

from src.evaluate import (
    full_report,
    print_report,
)
from sklearn.model_selection import (
    StratifiedKFold,
    cross_val_score,
)

# ============================================================
# 1. LOAD BEST HYPERPARAMETERS
# ============================================================

def load_best_params() -> dict:
    """
    Load hyperparameters generated by Optuna.

    If Optuna has not been executed yet, use safe fallback
    parameters so the final script can still run.
    """

    if os.path.exists(
        config.BEST_PARAMS_PATH
    ):
        with open(
            config.BEST_PARAMS_PATH,
            "r",
            encoding="utf-8",
        ) as file:

            params = json.load(file)

        print(
            "\nLoaded tuned hyperparameters "
            "from Optuna."
        )

        return params

    print(
        "\nWARNING:"
        "\nNo Optuna parameters were found."
        "\nUsing fallback XGBoost parameters."
        "\nFor best results, run:"
        "\npython -m src.hyperparameter_tuning"
    )

    return {
        "n_estimators": 400,
        "max_depth": 6,
        "learning_rate": 0.05,
        "subsample": 0.80,
        "colsample_bytree": 0.80,
        "min_child_weight": 3,
        "gamma": 0.5,
        "reg_alpha": 0.1,
        "reg_lambda": 1.0,
    }


# ============================================================
# 2. BUILD FINAL PIPELINE
# ============================================================

def build_final_pipeline(
    best_params,
    scale_pos_weight,
):
    """
    Build the final preprocessing + XGBoost pipeline.
    """

    model = XGBClassifier(
        **best_params,
        scale_pos_weight=scale_pos_weight,
        random_state=config.RANDOM_STATE,
        eval_metric="aucpr",
        n_jobs=-1,)

    pipeline = Pipeline(
        steps=[
            (
                "preprocessor",
                build_preprocessor(),
            ),
            (
                "model",
                model,
            ),
        ]
    )

    return pipeline
# ============================================================
# 3. STRATIFIED CROSS-VALIDATION
# ============================================================

def cross_validate(
    pipeline: Pipeline,
    X,
    y,
    n_splits: int = 5,):
    """
    Perform Stratified K-Fold Cross-Validation.

    Purpose:
        Check whether model performance is stable across
        different subsets of the training data.

    Important:
        Cross-validation is performed only on TRAINING data.

    Metric:
        Average Precision / PR-AUC
    """

    print("\n" + "=" * 70)
    print("STRATIFIED K-FOLD CROSS-VALIDATION")
    print("=" * 70)

    skf = StratifiedKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=config.RANDOM_STATE,)

    scores = cross_val_score(
        pipeline,
        X,
        y,
        cv=skf,
        scoring="average_precision",
        n_jobs=-1,)

    print(
        f"\nNumber of folds: {n_splits}")

    print(
        f"Mean PR-AUC: "
        f"{scores.mean():.4f}")

    print(
        f"Standard deviation: "
        f"{scores.std():.4f}")

    print(
        "\nFold PR-AUC scores:")

    for index, score in enumerate(
        scores,
        start=1,):
        print(
            f"Fold {index}: "
            f"{score:.4f}"
        )

    return scores
# ============================================================
# 4. FINAL TRAINING
# ============================================================

def run_final_training():

    print("\n" + "=" * 70)
    print("STEP 7 - FINAL MODEL TRAINING")
    print("=" * 70)

    # ========================================================
    # LOAD DATA
    # ========================================================
    (
        X_train,
        X_val,
        X_test,
        y_train,
        y_val,
        y_test,
    ) = get_clean_splits()

    print("\nDataset split:")
    print(f"Train: {X_train.shape}")
    print(f"Val  : {X_val.shape}")
    print(f"Test : {X_test.shape}")

    # ========================================================
    # FEATURE ENGINEERING
    # ========================================================

    X_train_fe = prepare_features(
        X_train
    )

    X_val_fe = prepare_features(
        X_val
    )

    X_test_fe = prepare_features(
        X_test
    )

    print(
        "\nFeature engineering completed.")
    # ========================================================
    # LOAD OPTUNA PARAMETERS
    # ========================================================

    best_params = load_best_params()

    print("\nFinal XGBoost parameters:")

    for parameter, value in best_params.items():
        print(
            f"  {parameter}: {value}")

    # ========================================================
    # CLASS IMBALANCE
    # IMPORTANT:
    # Calculate only from training labels.

    scale_pos_weight = get_scale_pos_weight(
        y_train)

    print(
        f"\nScale Pos Weight: "
        f"{scale_pos_weight:.4f}")

    # ========================================================
    # BUILD PIPELINE
    # ========================================================
    pipeline = build_final_pipeline(
        best_params,
        scale_pos_weight,)

    # ========================================================
    # CROSS-VALIDATION
    # ========================================================

    cv_scores = cross_validate(
        pipeline,
        X_train_fe,
        y_train,
        n_splits=5,
    )

    # ========================================================
    # FIT FINAL MODEL
    # ========================================================

    print("\n" + "=" * 70)
    print("FITTING FINAL MODEL")
    print("=" * 70)

    print(
        "\nTraining on complete training set...")
    pipeline.fit(
        X_train_fe,
        y_train,)

    print(
        "Final model training completed.")
    # ========================================================
    # VALIDATION PREDICTIONS
    # ========================================================

    print("\n" + "=" * 70)
    print("VALIDATION THRESHOLD OPTIMIZATION")
    print("=" * 70)

    val_proba = pipeline.predict_proba(
        X_val_fe
    )[:, 1]
    # --------------------------------------------------------
    # Find threshold using VALIDATION only
    # --------------------------------------------------------
    
    threshold_info = (
        find_cost_optimal_threshold(
            y_val,
            val_proba,
        ) )
    best_threshold = (
        threshold_info["best_threshold"] )

    minimum_cost = (
        threshold_info["min_cost"])

    print(
        f"\nOptimal decision threshold:"
        f" {best_threshold:.4f}")

    print(
        f"Minimum validation cost:"
        f" {minimum_cost:.2f}")
    # ========================================================
    # FINAL TEST EVALUATION
    # ========================================================

    print("\n" + "=" * 70)
    print("FINAL TEST SET EVALUATION")
    print("=" * 70)

    # Test data is touched ONLY here.

    test_proba = pipeline.predict_proba(
        X_test_fe
    )[:, 1]

    final_report = full_report(
        y_test,
        test_proba,
        threshold=best_threshold,
    )

    print_report(
        final_report,
        title="FINAL TEST SET RESULTS",
    )

    # ========================================================
    # SAVE MODEL
    # ========================================================

    print("\n" + "=" * 70)
    print("SAVING DEPLOYMENT ARTIFACTS")
    print("=" * 70)

    # Save complete pipeline.
    # This contains:
    #     preprocessing
    #     encoding
    #     scaling
    #     XGBoost model

    joblib.dump(
        pipeline,
        config.FINAL_MODEL_PATH,
    )

    # Save threshold separately.

    with open(
        config.THRESHOLD_PATH,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            {
                "threshold": float(
                    best_threshold
                )
            },
            file,
            indent=4,
        )

    print(
        f"\nModel saved to:"
        f"\n{config.FINAL_MODEL_PATH}"
    )

    print(
        f"\nThreshold saved to:"
        f"\n{config.THRESHOLD_PATH}"
    )

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print("\n" + "=" * 70)
    print("FINAL MODEL SUMMARY")
    print("=" * 70)

    print(
        f"Cross-validation mean PR-AUC: "
        f"{cv_scores.mean():.4f}"
    )

    print(
        f"Cross-validation std: "
        f"{cv_scores.std():.4f}"
    )

    print(
        f"Validation optimal threshold: "
        f"{best_threshold:.4f}"
    )

    print(
        f"Final test PR-AUC: "
        f"{final_report['pr_auc']:.4f}"
    )

    print(
        f"Final test Recall @ FPR: "
        f"{final_report['recall_at_target_fpr']:.4f}"
    )

    print("\nDeployment artifacts ready.")

    print("\nNext step:")
    print(
        "Build the API and add optional SMTP fraud alerts."
    )

    return (
        pipeline,
        best_threshold,
        final_report,
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    run_final_training()